---
# Configure cloudcli

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ cloudcli_services_enable }}"
  when: cloudcli_enable_service
